### ISSUE TITLE
Bad request when installing packs

### ISSUE THREAD

**Issue by chris-downs** [armab/st2mistral_and_ansible#1]
When I run the second part of the install in the readme I receive a 400 Bad Request:

```
> st2 run packs.install packs=st2mistral-and-ansible repo_url=armab/st2mistral-and-ansible
ERROR: 400 Client Error: Bad Request
MESSAGE: Additional properties are not allowed ('repo_url' was unexpected) for url: http://127.0.0.1:9101/v1/executions
```

**Comment by arm4b** [comment]
@chris-downs Thanks for the report!
It's fixed in https://github.com/armab/st2mistral_and_ansible/issues/2

Check updated pack contents and the README. You'll need to reinstall the pack.
